### ISSUE TITLE
This is a cool thing I want to do.

### ISSUE THREAD

**Issue by davidascher** [davidascher/issue-handler#18]
I think it should look like this:

[insert picture here]

@simonwex: ui-review?

**Comment by davidascher** [comment]
@simonwex: ui-review? `[this was magically recorded as a request]`:wave:

**Comment by davidascher** [comment]
@simonwex: ui-review? `[this was magically recorded as a request]`:wave:

**Comment by davidascher** [comment]
@simonwex: ui-review?
 `[this was magically recorded as a request]`:wave:

**Comment by davidascher** [comment]
@simonwex: ui-review? `[this was magically recorded as a request]`:wave:

**Comment by davidascher** [comment]
@simonwex: ui-review? `[this was magically recorded as a request]`:wave:

**Comment by davidascher** [comment]
@simonwex: ui-review?
 `[this was magically recorded as a request]`:wave:

**Comment by davidascher** [comment]
@ascherdavid: feedback? `[this was magically recorded as a request]`:wave:

**Comment by simonwex** [comment]
@davidascher, instead of "this was magically recorded as a request", a link to the thing that's doing this could be nice...

**Comment by davidascher** [comment]
Yes, totally, and good idea -- that's just placeholder text for now.

**Comment by ascherdavid** [comment]
blah

**Comment by ascherdavid** [comment]
asda

**Comment by simonwex** [comment]
sdfasdflkjasdflkfds

**Comment by simonwex** [comment]
@davidascher help!

**Comment by ascherdavid** [comment]
feedback+

**Comment by ascherdavid** [comment]
feedback+

**Comment by ascherdavid** [comment]
feedback+

**Comment by davidascher** [comment]
@ascherdavid: help?

**Comment by davidascher** [comment]
@ascherdavid: help?
 `[recording flag request]` http://mofo-mentions.herokuapp.com `[clearing flag]` http://mofo-mentions.herokuapp.com

**Comment by ascherdavid** [comment]
help+

**Comment by davidascher** [comment]
help?

**Comment by davidascher** [comment]
@ascherdavid: help? `[recording flag request]` http://mofo-mentions.herokuapp.com `[clearing flag]` http://mofo-mentions.herokuapp.com

**Comment by davidascher** [comment]
@ascherdavid: wtf? `[recording flag request]` http://mofo-mentions.herokuapp.com `[clearing flag]` http://mofo-mentions.herokuapp.com

**Comment by davidascher** [comment]
@aschedavid: wtf? `[recording flag request]` http://mofo-mentions.herokuapp.com `[clearing flag]` http://mofo-mentions.herokuapp.com

**Comment by ascherdavid** [comment]
wtf+

**Comment by ascherdavid** [comment]
foo+
